[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "cerebras-cloud-sdk>=0.1.0",
    "supermemory==3.0.0a25",
    "httpx>=0.24.0",
]
